### PR TITLE
Revert "General: Use std::array where applicable"

### PR DESCRIPTION
**Pull request by Antidote**
Reverts AxioDL/kabufuda#7

---
This change is [Reviewable](https://reviewable.io/reviews/axiodl/kabufuda/9)

### CODE REVIEW

**Comment by lioncash** [comment]
Was there a particular reason for reverting it?

**Comment by Antidote** [comment]
Yes, as I said in the original PR, std::array cannot be used in an anonymous union/struct.

EDIT:
Actually, looking at that PR, my comment I'm 99.9% sure I made is gone, not sure wtf happened there.

**Comment by lioncash** [comment]
Why can they not be used within an anonymous union/struct? They're an aggregate type.

**Comment by Antidote** [comment]
GCC claims they're not :/

**Comment by lioncash** [comment]
What is the compilation error in particular? Because I'm fairly sure a total revert is not necessary in this case. If it's related to a contained type within the array having a non-trivial default constructor, it's sufficient to just revert that section.

**Comment by Antidote** [comment]
```
../kabufuda/include/kabufuda/Directory.hpp:12:34: error: member ‘std::array<kabufuda::File, 127> kabufuda::Directory::<unnamed union>::<unnamed struct>::m_files’ with constructor not allowed in anonymous aggregate
   12 |       std::array<File, MaxFiles> m_files;
```

**Comment by lioncash** [comment]
Ah, this seems to be a result of the use of a compiler extension in the pre-existing code (where clang and MSVC are less restrictive). I can fix this in a new change.
